"""empty message

Revision ID: 9ed3610e9495
Revises: b1cbd33e8152
Create Date: 2019-05-09 19:29:33.349239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed3610e9495'
down_revision = 'b1cbd33e8152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_status', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('course_type_id', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('teacher_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'teacher_id')
    op.drop_column('courses', 'course_type_id')
    op.drop_column('courses', 'course_status')
    # ### end Alembic commands ###
